name: getx_boilerplate
description: "A new Flutter GetX project."

version: 1.0.0+1

environment:
  sdk: ">=3.9.2 <=4.0.0"

dependencies:
  flutter:
    sdk: flutter

  get: ^4.7.2
  get_storage: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/lang/en.json
    - assets/lang/ar.json
