name: getx_boilerplate
description: "A new Flutter GetX project."

version: 1.0.0+1

environment:
  sdk: ">=3.10.0 <=4.0.0"

dependencies:
  flutter:
    sdk: flutter

  get: ^4.7.2
  get_shimmer: ^0.0.6
  get_storage: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/lang/en.json
    - assets/lang/ar.json
    - assets/icons/
    - assets/images/
  fonts:
    - family: IBMPlexSansArabic
      fonts:
        - asset: assets/fonts/IBMPlexSansArabic-Regular.ttf
          weight: 400
        - asset: assets/fonts/IBMPlexSansArabic-Medium.ttf
          weight: 500
        - asset: assets/fonts/IBMPlexSansArabic-Bold.ttf
          weight: 700
        # - asset: assets/fonts/IBMPlexSansArabic-Thin.ttf
        #   weight: 100
        # - asset: assets/fonts/IBMPlexSansArabic-SemiBold.ttf
        #   weight: 600
        # - asset: assets/fonts/IBMPlexSansArabic-Light.ttf
        #   weight: 400
        # - asset: assets/fonts/IBMPlexSansArabic-ExtraLight.ttf
        #   weight: 500
        
